USE ROLE ACCOUNTADMIN;
USE WAREHOUSE XS_WH;
USE DATABASE GREGA_DATA_LAKE;

------------------------------------------------------------
-- SILVER.TRIP_DATA_DYNAMIC_TABLE – dynamic table version
------------------------------------------------------------

CREATE OR REPLACE DYNAMIC TABLE SILVER.TRIP_DATA_DYNAMIC_TABLE
    TARGET_LAG = '60 minutes'
    WAREHOUSE  = XS_WH
    REFRESH_MODE = AUTO
    INITIALIZE   = ON_CREATE
AS
    SELECT
        VENDORID                AS VENDOR_ID,
        TPEP_PICKUP_DATETIME    AS PICKUP_DATETIME,
        TPEP_DROPOFF_DATETIME   AS DROPOFF_DATETIME,
        PASSENGER_COUNT,
        TRIP_DISTANCE,
        RATECODEID              AS RATE_CODE_ID,
        STORE_AND_FWD_FLAG,
        PULOCATIONID            AS PU_LOCATION_ID,
        DOLOCATIONID            AS DO_LOCATION_ID,
        PAYMENT_TYPE,
        FARE_AMOUNT,
        EXTRA,
        MTA_TAX,
        TIP_AMOUNT,
        TOLLS_AMOUNT,
        IMPROVEMENT_SURCHARGE,
        TOTAL_AMOUNT,
        CONGESTION_SURCHARGE,
        AIRPORT_FEE,
        CBD_CONGESTION_FEE,
        ADM_FILENAME            AS ADM_SOURCE_FILENAME
    FROM BRONZE.TRIP_DATA
    WHERE TPEP_PICKUP_DATETIME IS NOT NULL
      AND TPEP_DROPOFF_DATETIME IS NOT NULL
      AND TPEP_DROPOFF_DATETIME > TPEP_PICKUP_DATETIME
      AND TRIP_DISTANCE >= 0
      AND FARE_AMOUNT >= 0
      AND TOTAL_AMOUNT >= 0
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY TPEP_PICKUP_DATETIME, TPEP_DROPOFF_DATETIME,
                     VENDORID, PULOCATIONID, DOLOCATIONID
        ORDER BY TPEP_PICKUP_DATETIME
    ) = 1;

    ALTER DYNAMIC TABLE SILVER.TRIP_DATA_DYNAMIC_TABLE SUSPEND;