USE ROLE TRAINING_ROLE;
USE DATABASE LSP_DB;
CREATE SCHEMA IF NOT EXISTS RAW_DATA;
CREATE SCHEMA IF NOT EXISTS MODELS;
CREATE STAGE IF NOT EXISTS MODELS.SPROC_STAGE;
CREATE SCHEMA IF NOT EXISTS ORCHESTRATION;

CREATE WAREHOUSE IF NOT EXISTS ML_WH WITH
     WAREHOUSE_SIZE='XSMALL'
     AUTO_SUSPEND = 120
;