USE ROLE TRAINING_ROLE;
USE DATABASE LSP_DB;
CREATE SCHEMA IF NOT EXISTS RAW_DATA;
-- CREATE SCHEMA IF NOT EXISTS FEATURES;
CREATE SCHEMA IF NOT EXISTS MODELS;

CREATE WAREHOUSE IF NOT EXISTS ML_WH WITH
     WAREHOUSE_SIZE='X-SMALL'
     AUTO_SUSPEND = 120
;