CREATE OR REPLACE TASK  ORCHESTRATION.DAILY_DEMAND_FORECAST
  WAREHOUSE = ML_WH
  SCHEDULE = 'USING CRON 0 0 * * * UTC'
AS
BEGIN
    CALL MODELS.DAILY_DEMAND_FORECAST(
    TO_VARCHAR(CURRENT_DATE(), 'YYYY-MM-DD')
    );
    LET forecast_date := TO_VARCHAR(CURRENT_DATE(), 'YYYY-MM-DD');
    CALL SYSTEM$SET_RETURN_VALUE(:forecast_date);
END;

CREATE OR REPLACE TASK SEND_EMAIL
  WAREHOUSE = ML_WH
AFTER  ORCHESTRATION.DAILY_DEMAND_FORECAST
AS
BEGIN
    LET VALUE := (SELECT SYSTEM$GET_PREDECESSOR_RETURN_VALUE('DAILY_DEMAND_FORECAST'));
    CALL SYSTEM$SET_RETURN_VALUE('Email report sent!');
END;

ALTER TASK SEND_EMAIL RESUME;
